### ISSUE TITLE
Setup emacs have error

### ISSUE THREAD

**Issue by xiongchenyu6** [harsman/dyalog-mode#3]
```
      ]load /Users/chenyu/.emacs.d/.local/straight/repos/dyalog-mode/Emacs.apl
#.Emacs.editor.Emacs
      Emacs.editor.setupmenu ⍬
VALUE ERROR
setupmenu[2] '⎕SE.popup.emacs'⎕WC'MenuItem'('Caption'('Edit in Emacs',⎕AV[10],
      title))
```
System : Macos Monterey
Emacs versiont : 29.05

**Comment by harsman** [comment]
The MacOS version of Dyalog does not have an IDE, so you can't use that part of setup, it only works on Windows.

I've never used Dyalog on a Mac, but you could try using the experimental RIDE support in dyalog mode to get a session in Emacs for a Dyalog process running on your Mac. Do M-x dyalog-ride-session from Emacs and enter the host and port that Dyalog is listening for ride connections on. This will give you a session prompt where you can enter expressions or open the editor etc. Even debugging works.

I never documented this because it was new and not thoroughly tested but it should work.
