### ISSUE TITLE
Editor setup fails

### ISSUE THREAD

**Issue by jvasile** [harsman/dyalog-mode#7]
I wanted to try some APL, and I was happy to see this mode exists.  I tried to follow the setup instructions, but received an error on setting up the editor:

```
]load /home/james/.emacs.d/elpa/dyalog-mode-20230214.1027/Emacs.apl
#.Emacs
Emacs.editor.setupmenu ⍬
VALUE ERROR
setupmenu[2] '⎕SE.popup.emacs'⎕WC'MenuItem'('Caption'('Edit in Emacs',⎕AV[10],
      title))
```

Here's some info about my system:
```
DE:
  Version: 4.5.4097
  Electron: 26.6.9
  Chrome: 116.0.5845.228
  Node: 18.16.1
  Platform: Linux x86_64
  Date: 2024-02-23 15:24:25 +0100
  Git commit: 9fb313638328832b51012bd75b2523a8d97f4509
  Preferences:{
    "defaultConfig":"v19.0",
    "kbdLocale":"en_US",
    "presetsCreated":"[\"/opt/mdyalog/19.0/64/unicode/mapl\"]"
  }

Interpreter:
  Version: 19.0.50027
  Platform: Linux-64
  Edition: Unicode/64
  Date: Aug 21 2024 at 00:47:48
```

**Comment by harsman** [comment]
The IDE integration only works on Windows, but you can use the newer RIDE interface to connect to Dyalog from Emacs.

If you set the RIDE_INIT environment variable to serve::<port> you should be able to just run M-x dyalog-ride-session from Emacs and then enter localhost and the port number you set in RIDE_INIT.

This is undocumented because I just got it working and haven't really polished it (I don't think you can send a command to edit something for example) but entering expressions in the session and debugging works.

**Comment by jvasile** [comment]
Thanks much, I'll give it a try!
